name: Build and Release

jobs:
  build_and_release:
    type: build
    params:
      platform: android
      profile: production
    post_build:
      - name: Create GitHub Release
        uses: github_release
        with:
          tag_name: v${{ expo.version }}
          release_name: GeoShot v${{ expo.version }}
          generate_release_notes: true
          files:
            - "*.apk"
            - "*.aab"
