name: Create Production Builds and Release

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production
    post_build:
      - name: Create GitHub Release
        uses: github_release
        with:
          tag_name: v${{ expo.version }}
          release_name: GeoShot v${{ expo.version }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files:
            - "app-armeabi-v7a-release.apk"
            - "app-arm64-v8a-release.apk"
            - "app-x86-release.apk"
            - "app-x86_64-release.apk"
            - "app-universal-release.apk"
            - "*.aab"
  
  # build_ios:
  #   type: build
  #   params:
  #     platform: ios
  #     profile: production
  #   post_build:
  #     - name: Create GitHub Release
  #       uses: github_release
  #       with:
  #         tag_name: v${{ expo.version }}-ios
  #         release_name: GeoShot v${{ expo.version }} (iOS)
  #         generate_release_notes: true
  #         draft: false
  #         prerelease: false
  #         files:
  #           - "*.ipa"
