name: Build and Update on Push

on:
  push:
    branches:
      - main

jobs:
  publish_update:
    type: update
    params:
      channel: production
      message: ${{ github.event.head_commit.message }}
