import { StyleSheet } from 'react-native';

export const previewStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#000',
        gap: 16,
    },
    loadingText: {
        fontSize: 16,
        color: '#fff',
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#000',
        padding: 20,
    },
    errorText: {
        fontSize: 18,
        color: '#ff5555',
        textAlign: 'center',
        marginBottom: 24,
    },
    button: {
        backgroundColor: '#fff',
        paddingHorizontal: 32,
        paddingVertical: 16,
        borderRadius: 12,
    },
    buttonText: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: '#000',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#000',
    },
    headerButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    headerButton: {
        width: 48,
        height: 48,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600' as const,
        color: '#fff',
    },
    content: {
        padding: 16,
    },
    previewContainer: {
        borderRadius: 12,
        overflow: 'hidden',
        marginBottom: 24,
        backgroundColor: '#1a1a1a',
    },
    image: {
        width: '100%',
        aspectRatio: 3 / 4,
    },
    imagePortrait: {
        width: '100%',
        aspectRatio: 1,
    },
    info: {
        backgroundColor: '#1a1a1a',
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
    },
    infoTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 20,
    },
    infoTitle: {
        fontSize: 20,
        fontWeight: '700' as const,
        color: '#fff',
        letterSpacing: 0.5,
    },
    infoRow: {
        backgroundColor: '#262626',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        marginBottom: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#4CAF50',
    },
    infoLabel: {
        fontSize: 12,
        color: '#aaa',
        fontWeight: '600' as const,
        letterSpacing: 0.3,
        marginBottom: 6,
        textTransform: 'uppercase',
    },
    infoValue: {
        fontSize: 15,
        color: '#fff',
        fontWeight: '500' as const,
        flex: 1,
        textAlign: 'left',
    },
    infoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    applyButton: {
        backgroundColor: '#4CAF50',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 8,
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    applyButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '700',
        letterSpacing: 0.3,
    },
    input: {
        backgroundColor: '#333333',
        color: '#fff',
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderRadius: 10,
        fontSize: 14,
        textAlign: 'left',
        borderWidth: 2,
        borderColor: '#4CAF50',
        marginTop: 8,
    },
    multilineInput: {
        minHeight: 80,
        textAlignVertical: 'top',
        textAlign: 'left',
    },
});
